pipeline {
    agent { any { image 'python:3.5.1' } }
    tools {
        python3 'python3'
    }
    stages {
        stage('show_directory') {
            steps {
                sh 'ls -la'
            }
        }
        stage('build') {
            steps {
                sh 'python3 -m pip install -r tools/cloud_functions/gcs_event_based_ingest/requirements-dev.txt'
            }
        }
    }
}
