pipeline {
    agent { docker { image 'python:3.8.2' } }
    stages {
        stage('install_requirements') {
            steps {
                sh 'rm -rf bigquery-utils # Used when building on controller node'
                sh 'git clone https://github.com/mschaszberger/bigquery-utils.git'
                sh 'python3 -m pip install --user -r bigquery-utils/tools/cloud_functions/gcs_event_based_ingest/requirements-dev.txt'
            }
        }
        stage('unit_tests') {
            steps {
                sh '-c python3 -m pytest tests -m "not IT"'
            }
        }
        stage('integration_tests') {
            steps {
                sh '-c python3 -m pytest tests -m IT'
            }
        }
    }
}
